<?xml version="1.0" encoding="utf-8"?><Database Name="KAHYToon" EntityNamespace="QLKAHYTOON.Models" ContextNamespace="QLKAHYTOON.Models" Class="QLKAHYTOONDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="ConnectionString" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=KAHYToon;Integrated Security=True;TrustServerCertificate=True" Provider="System.Data.SqlClient" />
  <Table Name="dbo.admin" Member="admins">
    <Type Name="admin">
      <Column Name="MaAdmin" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDangNhap" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="VaiTro" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="admin_baocao" Member="baocaos" ThisKey="MaAdmin" OtherKey="MaAdminXuLy" Type="baocao" />
    </Type>
  </Table>
  <Table Name="dbo.baocao" Member="baocaos">
    <Type Name="baocao">
      <Column Name="MaBaoCao" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNguoiDung" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaAdminXuLy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaTruyen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaChuong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NoiDungBaoCao" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayBaoCao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="admin_baocao" Member="admin" ThisKey="MaAdminXuLy" OtherKey="MaAdmin" Type="admin" IsForeignKey="true" />
      <Association Name="chuong_baocao" Member="chuong" ThisKey="MaChuong" OtherKey="MaChuong" Type="chuong" IsForeignKey="true" />
      <Association Name="nguoidung_baocao" Member="nguoidung" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="nguoidung" IsForeignKey="true" />
      <Association Name="thongtintruyen_baocao" Member="thongtintruyen" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="thongtintruyen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.chuong" Member="chuongs">
    <Type Name="chuong">
      <Column Name="MaChuong" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTruyen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoChuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenChuong" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AnhChuong" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayDang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="chuong_baocao" Member="baocaos" ThisKey="MaChuong" OtherKey="MaChuong" Type="baocao" />
      <Association Name="chuong_binhluan" Member="binhluans" ThisKey="MaChuong" OtherKey="MaChuong" Type="binhluan" />
      <Association Name="chuong_lichsudoc" Member="lichsudocs" ThisKey="MaChuong" OtherKey="MaChuong" Type="lichsudoc" />
      <Association Name="thongtintruyen_chuong" Member="thongtintruyen" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="thongtintruyen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.nguoidung" Member="nguoidungs">
    <Type Name="nguoidung">
      <Column Name="MaNguoiDung" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDangNhap" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="NgayDangKy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VaiTro" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThoiGianDangNhap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IP_DangNhap" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="Avatar" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="nguoidung_baocao" Member="baocaos" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="baocao" />
      <Association Name="nguoidung_truyenyeuthich" Member="truyenyeuthiches" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="truyenyeuthich" />
      <Association Name="nguoidung_binhluan" Member="binhluans" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="binhluan" />
      <Association Name="nguoidung_danhgia" Member="danhgias" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="danhgia" />
      <Association Name="nguoidung_lichsudoc" Member="lichsudocs" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="lichsudoc" />
    </Type>
  </Table>
  <Table Name="dbo.theloai" Member="theloais">
    <Type Name="theloai">
      <Column Name="MaTheLoai" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTheLoai" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="theloai_truyen_theloai" Member="truyen_theloais" ThisKey="MaTheLoai" OtherKey="MaTheLoai" Type="truyen_theloai" />
    </Type>
  </Table>
  <Table Name="dbo.truyenyeuthich" Member="truyenyeuthiches">
    <Type Name="truyenyeuthich">
      <Column Name="MaNguoiDung" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTruyen" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayThem" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="nguoidung_truyenyeuthich" Member="nguoidung" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="nguoidung" IsForeignKey="true" />
      <Association Name="thongtintruyen_truyenyeuthich" Member="thongtintruyen" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="thongtintruyen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.binhluan" Member="binhluans">
    <Type Name="binhluan">
      <Column Name="MaBinhLuan" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNguoiDung" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaTruyen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaChuong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayDang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoChuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaBinhLuanCha" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LuotLike" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="binhluan_binhluan" Member="binhluans" ThisKey="MaBinhLuan" OtherKey="MaBinhLuanCha" Type="binhluan" />
      <Association Name="binhluan_binhluan" Member="binhluan1" ThisKey="MaBinhLuanCha" OtherKey="MaBinhLuan" Type="binhluan" IsForeignKey="true" />
      <Association Name="chuong_binhluan" Member="chuong" ThisKey="MaChuong" OtherKey="MaChuong" Type="chuong" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="nguoidung_binhluan" Member="nguoidung" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="nguoidung" IsForeignKey="true" />
      <Association Name="thongtintruyen_binhluan" Member="thongtintruyen" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="thongtintruyen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.thongtintruyen" Member="thongtintruyens">
    <Type Name="thongtintruyen">
      <Column Name="MaTruyen" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTheLoai" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TenTruyen" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TacGia" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NgayDang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="AnhTruyen" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Slug" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LuotXem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LuotThich" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="thongtintruyen_baocao" Member="baocaos" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="baocao" />
      <Association Name="thongtintruyen_chuong" Member="chuongs" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="chuong" />
      <Association Name="thongtintruyen_truyenyeuthich" Member="truyenyeuthiches" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="truyenyeuthich" />
      <Association Name="thongtintruyen_binhluan" Member="binhluans" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="binhluan" />
      <Association Name="thongtintruyen_danhgia" Member="danhgias" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="danhgia" />
      <Association Name="thongtintruyen_lichsudoc" Member="lichsudocs" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="lichsudoc" />
      <Association Name="thongtintruyen_truyen_theloai" Member="truyen_theloais" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="truyen_theloai" />
    </Type>
  </Table>
  <Table Name="dbo.danhgia" Member="danhgias">
    <Type Name="danhgia">
      <Column Name="MaNguoiDung" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTruyen" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoSao" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayDanhGia" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="nguoidung_danhgia" Member="nguoidung" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="nguoidung" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="thongtintruyen_danhgia" Member="thongtintruyen" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="thongtintruyen" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.lichsudoc" Member="lichsudocs">
    <Type Name="lichsudoc">
      <Column Name="MaLichSuDoc" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNguoiDung" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaTruyen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaChuong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThoiGianDoc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="chuong_lichsudoc" Member="chuong" ThisKey="MaChuong" OtherKey="MaChuong" Type="chuong" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="nguoidung_lichsudoc" Member="nguoidung" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="nguoidung" IsForeignKey="true" />
      <Association Name="thongtintruyen_lichsudoc" Member="thongtintruyen" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="thongtintruyen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.truyen_theloai" Member="truyen_theloais">
    <Type Name="truyen_theloai">
      <Column Name="MaTruyen" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTheLoai" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="theloai_truyen_theloai" Member="theloai" ThisKey="MaTheLoai" OtherKey="MaTheLoai" Type="theloai" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="thongtintruyen_truyen_theloai" Member="thongtintruyen" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="thongtintruyen" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_GetTopTruyenByView" Method="sp_GetTopTruyenByView">
    <Parameter Name="ThoiGian" Parameter="thoiGian" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="sp_GetTopTruyenByViewResult">
      <Column Name="MaTruyen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenTruyen" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AnhTruyen" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TacGia" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TenTheLoai" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Admin_DuyetBaoCao" Method="sp_Admin_DuyetBaoCao">
    <Parameter Name="MaBaoCao" Parameter="maBaoCao" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="MaAdminXuLy" Parameter="maAdminXuLy" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_GetDanhSachChuong" Method="sp_GetDanhSachChuong">
    <Parameter Name="MaTruyen" Parameter="maTruyen" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="sp_GetDanhSachChuongResult">
      <Column Name="MaChuong" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaTruyen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoChuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenChuong" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AnhChuong" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayDang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Admin_KhoaTaiKhoan" Method="sp_Admin_KhoaTaiKhoan">
    <Parameter Name="MaNguoiDung" Parameter="maNguoiDung" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Admin_SuaChuong" Method="sp_Admin_SuaChuong">
    <Parameter Name="MaChuong" Parameter="maChuong" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="TenChuong" Parameter="tenChuong" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="AnhChuong" Parameter="anhChuong" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Admin_SuaTheLoai" Method="sp_Admin_SuaTheLoai">
    <Parameter Name="MaTheLoai" Parameter="maTheLoai" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="TenTheLoai" Parameter="tenTheLoai" Type="System.String" DbType="NVarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Admin_ThemChuong" Method="sp_Admin_ThemChuong">
    <Parameter Name="MaChuong" Parameter="maChuong" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="MaTruyen" Parameter="maTruyen" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="SoChuong" Parameter="soChuong" Type="System.Int32" DbType="Int" />
    <Parameter Name="TenChuong" Parameter="tenChuong" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="AnhChuong" Parameter="anhChuong" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Admin_ThemTheLoai" Method="sp_Admin_ThemTheLoai">
    <Parameter Name="MaTheLoai" Parameter="maTheLoai" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="TenTheLoai" Parameter="tenTheLoai" Type="System.String" DbType="NVarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Admin_ThongKeTongQuan" Method="sp_Admin_ThongKeTongQuan">
    <ElementType Name="sp_Admin_ThongKeTongQuanResult">
      <Column Name="TongTruyen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongNguoiDung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongLuotXem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BaoCaoMoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Admin_XoaBinhLuan" Method="sp_Admin_XoaBinhLuan">
    <Parameter Name="MaBinhLuan" Parameter="maBinhLuan" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Admin_XoaChuong" Method="sp_Admin_XoaChuong">
    <Parameter Name="MaChuong" Parameter="maChuong" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Admin_XoaTheLoai" Method="sp_Admin_XoaTheLoai">
    <Parameter Name="MaTheLoai" Parameter="maTheLoai" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Admin_XoaTruyen" Method="sp_Admin_XoaTruyen">
    <Parameter Name="MaTruyen" Parameter="maTruyen" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_GetBinhLuanByTruyen" Method="sp_GetBinhLuanByTruyen">
    <Parameter Name="MaTruyen" Parameter="maTruyen" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="sp_GetBinhLuanByTruyenResult">
      <Column Name="MaBinhLuan" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayDang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Avatar" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_User_CapNhatThongTin" Method="sp_User_CapNhatThongTin">
    <Parameter Name="MaNguoiDung" Parameter="maNguoiDung" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="HoTen" Parameter="hoTen" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Avatar" Parameter="avatar" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="SoDienThoai" Parameter="soDienThoai" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_User_GuiBinhLuan" Method="sp_User_GuiBinhLuan">
    <Parameter Name="MaBinhLuan" Parameter="maBinhLuan" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="MaNguoiDung" Parameter="maNguoiDung" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="MaTruyen" Parameter="maTruyen" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="NoiDung" Parameter="noiDung" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_User_DangKy" Method="sp_User_DangKy">
    <Parameter Name="MaNguoiDung" Parameter="maNguoiDung" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="HoTen" Parameter="hoTen" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="TenDangNhap" Parameter="tenDangNhap" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="MatKhau" Parameter="matKhau" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_User_DangNhap" Method="sp_User_DangNhap">
    <Parameter Name="TenDangNhap" Parameter="tenDangNhap" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="MatKhau" Parameter="matKhau" Type="System.String" DbType="NVarChar(255)" />
    <ElementType Name="sp_User_DangNhapResult">
      <Column Name="MaNguoiDung" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenDangNhap" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="NgayDangKy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VaiTro" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThoiGianDangNhap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IP_DangNhap" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="Avatar" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_User_DoiMatKhau" Method="sp_User_DoiMatKhau">
    <Parameter Name="MaNguoiDung" Parameter="maNguoiDung" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="MatKhauMoi" Parameter="matKhauMoi" Type="System.String" DbType="NVarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_User_GuiBaoCao" Method="sp_User_GuiBaoCao">
    <Parameter Name="MaBaoCao" Parameter="maBaoCao" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="MaNguoiDung" Parameter="maNguoiDung" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="MaTruyen" Parameter="maTruyen" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="MaChuong" Parameter="maChuong" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="NoiDungBaoCao" Parameter="noiDungBaoCao" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Admin_SuaTruyen" Method="sp_Admin_SuaTruyen">
    <Parameter Name="MaTruyen" Parameter="maTruyen" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="MaTheLoai" Parameter="maTheLoai" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="TenTruyen" Parameter="tenTruyen" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="TacGia" Parameter="tacGia" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="TrangThai" Parameter="trangThai" Type="System.String" DbType="NVarChar(40)" />
    <Parameter Name="AnhTruyen" Parameter="anhTruyen" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Slug" Parameter="slug" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Admin_ThemTruyen" Method="sp_Admin_ThemTruyen">
    <Parameter Name="MaTruyen" Parameter="maTruyen" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="MaTheLoai" Parameter="maTheLoai" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="TenTruyen" Parameter="tenTruyen" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="TacGia" Parameter="tacGia" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="TrangThai" Parameter="trangThai" Type="System.String" DbType="NVarChar(40)" />
    <Parameter Name="AnhTruyen" Parameter="anhTruyen" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Slug" Parameter="slug" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Admin_ThemAdmin" Method="sp_Admin_ThemAdmin">
    <Parameter Name="MaAdmin" Parameter="maAdmin" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="TenDangNhap" Parameter="tenDangNhap" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="MatKhau" Parameter="matKhau" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="HoTen" Parameter="hoTen" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Admin_XoaAdmin" Method="sp_Admin_XoaAdmin">
    <Parameter Name="MaAdmin" Parameter="maAdmin" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_GetTruyenDeCu" Method="sp_GetTruyenDeCu">
    <ElementType Name="sp_GetTruyenDeCuResult">
      <Column Name="MaTruyen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenTruyen" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AnhTruyen" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TacGia" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TenTheLoai" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetTruyenHotSlider" Method="sp_GetTruyenHotSlider">
    <ElementType Name="sp_GetTruyenHotSliderResult">
      <Column Name="MaTruyen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenTruyen" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AnhTruyen" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TacGia" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MaTheLoai" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TenTheLoai" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetTruyenMoiNhat" Method="sp_GetTruyenMoiNhat">
    <Parameter Name="SoLuong" Parameter="soLuong" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_GetTruyenMoiNhatResult">
      <Column Name="MaTruyen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenTruyen" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AnhTruyen" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TacGia" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MaTheLoai" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TenTheLoai" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>