<?xml version="1.0" encoding="utf-8"?><Database Name="KAHYToon" EntityNamespace="QLKAHYTOON.Models" ContextNamespace="QLKAHYTOON.Models" Class="QLKAHYTOONDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.admin" Member="admins">
    <Type Name="admin">
      <Column Name="MaAdmin" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDangNhap" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="VaiTro" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="admin_baocao" Member="baocaos" ThisKey="MaAdmin" OtherKey="MaAdminXuLy" Type="baocao" />
    </Type>
  </Table>
  <Table Name="dbo.baocao" Member="baocaos">
    <Type Name="baocao">
      <Column Name="MaBaoCao" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNguoiDung" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaAdminXuLy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaTruyen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaChuong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NoiDungBaoCao" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayBaoCao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="admin_baocao" Member="admin" ThisKey="MaAdminXuLy" OtherKey="MaAdmin" Type="admin" IsForeignKey="true" />
      <Association Name="chuong_baocao" Member="chuong" ThisKey="MaChuong" OtherKey="MaChuong" Type="chuong" IsForeignKey="true" />
      <Association Name="nguoidung_baocao" Member="nguoidung" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="nguoidung" IsForeignKey="true" />
      <Association Name="thongtintruyen_baocao" Member="thongtintruyen" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="thongtintruyen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.binhluan" Member="binhluans">
    <Type Name="binhluan">
      <Column Name="MaBinhLuan" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNguoiDung" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaTruyen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaChuong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayDang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoChuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="chuong_binhluan" Member="chuong" ThisKey="MaChuong" OtherKey="MaChuong" Type="chuong" IsForeignKey="true" />
      <Association Name="nguoidung_binhluan" Member="nguoidung" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="nguoidung" IsForeignKey="true" />
      <Association Name="thongtintruyen_binhluan" Member="thongtintruyen" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="thongtintruyen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.chuong" Member="chuongs">
    <Type Name="chuong">
      <Column Name="MaChuong" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTruyen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoChuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenChuong" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AnhChuong" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayDang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="chuong_baocao" Member="baocaos" ThisKey="MaChuong" OtherKey="MaChuong" Type="baocao" />
      <Association Name="chuong_binhluan" Member="binhluans" ThisKey="MaChuong" OtherKey="MaChuong" Type="binhluan" />
      <Association Name="chuong_lichsudoc" Member="lichsudocs" ThisKey="MaChuong" OtherKey="MaChuong" Type="lichsudoc" />
      <Association Name="thongtintruyen_chuong" Member="thongtintruyen" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="thongtintruyen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.danhgia" Member="danhgias">
    <Type Name="danhgia">
      <Column Name="MaNguoiDung" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTruyen" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoSao" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BinhLuan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayBinhLuan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="nguoidung_danhgia" Member="nguoidung" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="nguoidung" IsForeignKey="true" />
      <Association Name="thongtintruyen_danhgia" Member="thongtintruyen" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="thongtintruyen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.lichsudoc" Member="lichsudocs">
    <Type Name="lichsudoc">
      <Column Name="MaLichSuDoc" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNguoiDung" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaTruyen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaChuong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThoiGianDoc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayXem" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="chuong_lichsudoc" Member="chuong" ThisKey="MaChuong" OtherKey="MaChuong" Type="chuong" IsForeignKey="true" />
      <Association Name="nguoidung_lichsudoc" Member="nguoidung" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="nguoidung" IsForeignKey="true" />
      <Association Name="thongtintruyen_lichsudoc" Member="thongtintruyen" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="thongtintruyen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.nguoidung" Member="nguoidungs">
    <Type Name="nguoidung">
      <Column Name="MaNguoiDung" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDangNhap" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="NgayDangKy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VaiTro" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThoiGianDangNhap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IP_DangNhap" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="Avatar" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="nguoidung_baocao" Member="baocaos" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="baocao" />
      <Association Name="nguoidung_binhluan" Member="binhluans" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="binhluan" />
      <Association Name="nguoidung_danhgia" Member="danhgias" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="danhgia" />
      <Association Name="nguoidung_lichsudoc" Member="lichsudocs" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="lichsudoc" />
      <Association Name="nguoidung_truyenyeuthich" Member="truyenyeuthiches" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="truyenyeuthich" />
    </Type>
  </Table>
  <Table Name="dbo.theloai" Member="theloais">
    <Type Name="theloai">
      <Column Name="MaTheLoai" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTheLoai" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="theloai_thongtintruyen" Member="thongtintruyens" ThisKey="MaTheLoai" OtherKey="MaTheLoai" Type="thongtintruyen" />
    </Type>
  </Table>
  <Table Name="dbo.thongtintruyen" Member="thongtintruyens">
    <Type Name="thongtintruyen">
      <Column Name="MaTruyen" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTheLoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenTruyen" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TacGia" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NgayDang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="AnhTruyen" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Slug" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="thongtintruyen_baocao" Member="baocaos" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="baocao" />
      <Association Name="thongtintruyen_binhluan" Member="binhluans" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="binhluan" />
      <Association Name="thongtintruyen_chuong" Member="chuongs" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="chuong" />
      <Association Name="thongtintruyen_danhgia" Member="danhgias" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="danhgia" />
      <Association Name="thongtintruyen_lichsudoc" Member="lichsudocs" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="lichsudoc" />
      <Association Name="thongtintruyen_truyenyeuthich" Member="truyenyeuthiches" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="truyenyeuthich" />
      <Association Name="theloai_thongtintruyen" Member="theloai" ThisKey="MaTheLoai" OtherKey="MaTheLoai" Type="theloai" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.truyenyeuthich" Member="truyenyeuthiches">
    <Type Name="truyenyeuthich">
      <Column Name="MaNguoiDung" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTruyen" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayThem" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="nguoidung_truyenyeuthich" Member="nguoidung" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="nguoidung" IsForeignKey="true" />
      <Association Name="thongtintruyen_truyenyeuthich" Member="thongtintruyen" ThisKey="MaTruyen" OtherKey="MaTruyen" Type="thongtintruyen" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_GetTruyenMoiNhat" Method="sp_GetTruyenMoiNhat">
    <Parameter Name="SoLuong" Parameter="soLuong" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_GetTruyenMoiNhatResult">
      <Column Name="MaTruyen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenTruyen" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AnhTruyen" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TacGia" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TenTheLoai" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetTruyenDeCu" Method="sp_GetTruyenDeCu">
    <ElementType Name="sp_GetTruyenDeCuResult">
      <Column Name="MaTruyen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenTruyen" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AnhTruyen" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TacGia" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TenTheLoai" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetTopTruyenByView" Method="sp_GetTopTruyenByView">
    <Parameter Name="ThoiGian" Parameter="thoiGian" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="sp_GetTopTruyenByViewResult">
      <Column Name="MaTruyen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenTruyen" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AnhTruyen" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TacGia" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TenTheLoai" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetTruyenHotSlider" Method="sp_GetTruyenHotSlider">
    <ElementType Name="sp_GetTruyenHotSliderResult">
      <Column Name="MaTruyen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenTruyen" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AnhTruyen" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TacGia" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MaTheLoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenTheLoai" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>